package com.myapp.tools.media.renamer.view.swing;

/**
 * helds the action commands for the listeners.
 * 
 * @author andre
 */
interface IActionCommands {
    String ADD_FILES = "FILE_ADD";
    String REMOVE_SELECTED_FILES = "REMOVE_SELECTED_FILES";
    String MOVE_SELECTED_FILES = "MOVE_SELECTED_FILES";
    String REMOVE_ALL_FILES = "REMOVE_ALL_FILES";
    String EXIT_APP = "EXIT_APP";
    String EDIT_COPY_SETTINGS = "EDIT_COPY_SETTINGS";
    String EDIT_ALL_SETTINGS = "EDIT_ALL_SETTINGS";
    
    String SET_TITEL_TO_ALL = "SET_TITEL_TO_ALL";
    String SET_THEMA_TO_ALL = "SET_THEMA_TO_ALL";
    String SET_BESCHREIBUNG_TO_ALL = "SET_BESCHREIBUNG_TO_ALL";
    String EDIT_FILTER = "EDIT_FILTER";

    String SET_BESCHREIBUNG_TO_SELECTION = "SET_BESCHREIBUNG_TO_SELECTION";
    String SET_THEMA_TO_SELECTION = "SET_THEMA_TO_SELECTION";
    String SET_TITEL_TO_SELECTION = "SET_TITEL_TO_SELECTION";

    String SET_BESCHREIBUNG_TO_UNCHANGED = "SET_BESCHREIBUNG_TO_UNCHANGED";
    String SET_THEMA_TO_UNCHANGED = "SET_THEMA_TO_UNCHANGED";
    String SET_TITEL_TO_UNCHANGED = "SET_TITEL_TO_UNCHANGED";
    
    String START_RENAME_PROCESS = "START_RENAME_PROCESS";
    String SHOW_LOG_HISTORY = "SHOW_LOG_HISTORY";

    String SET_NUMMERIERUNG_TO_SELECTION = "SET_NUMMERIERUNG_TO_SELECTION";
    String DISCARD_SELECTIONS_CHANGES = "DISCARD_SELECTIONS_CHANGES";
    String DISCARD_ALL_CHANGES = "DISCARD_ALL_CHANGES";
    
    String SHOW_COPYRIGHT = "SHOW_COPYRIGHT";
    String EDIT_DATE_FORMAT = "EDIT_DATE_FORMAT";
    
    
    /**swing application specific*/
    String SET_SYSTEM_LOOK_AND_FEEL = "SET_SYSTEM_LOOK_AND_FEEL";
    
    /**swing application specific*/
    String SET_CROSS_PLATFORM_LOOK_AND_FEEL ="SET_CROSS_PLATFORM_LOOK_AND_FEEL";
    String SET_NUMMERIERUNG_START = "SET_NUMMERIERUNG_START";
}
